#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("iReach_Android.Resource", IsApplication=true)]

namespace iReach_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::api_interaction_kit.Resource.String.ApplicationName = global::iReach_Android.Resource.String.ApplicationName;
			global::api_interaction_kit.Resource.String.Hello = global::iReach_Android.Resource.String.Hello;
			global::api_interaction_kit.Resource.String.library_name = global::iReach_Android.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int sensor_settings = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int iReach_Logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060022
			public const int Create_User_Button = 2131099682;
			
			// aapt resource value: 0x7f06002a
			public const int age = 2131099690;
			
			// aapt resource value: 0x7f060011
			public const int auto_complete_food = 2131099665;
			
			// aapt resource value: 0x7f060018
			public const int b_user_activity = 2131099672;
			
			// aapt resource value: 0x7f060009
			public const int create_age = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int create_doctor_spinner = 2131099660;
			
			// aapt resource value: 0x7f060000
			public const int create_email = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int create_firstn = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int create_gender_radio = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int create_group_spinner = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int create_height = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int create_lastn = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int create_password = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int create_submit_btn = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int create_weight = 2131099656;
			
			// aapt resource value: 0x7f06002d
			public const int doctor = 2131099693;
			
			// aapt resource value: 0x7f060026
			public const int email = 2131099686;
			
			// aapt resource value: 0x7f06001d
			public const int email_text_field = 2131099677;
			
			// aapt resource value: 0x7f060006
			public const int female_radio_btn = 2131099654;
			
			// aapt resource value: 0x7f060027
			public const int first_name = 2131099687;
			
			// aapt resource value: 0x7f060019
			public const int food_button = 2131099673;
			
			// aapt resource value: 0x7f060024
			public const int force_push_button = 2131099684;
			
			// aapt resource value: 0x7f060029
			public const int gender = 2131099689;
			
			// aapt resource value: 0x7f06002e
			public const int group = 2131099694;
			
			// aapt resource value: 0x7f06002c
			public const int height = 2131099692;
			
			// aapt resource value: 0x7f06001b
			public const int imageView1 = 2131099675;
			
			// aapt resource value: 0x7f060028
			public const int last_name = 2131099688;
			
			// aapt resource value: 0x7f060016
			public const int linearLayout1 = 2131099670;
			
			// aapt resource value: 0x7f060021
			public const int login_button = 2131099681;
			
			// aapt resource value: 0x7f06001f
			public const int password_text_field = 2131099679;
			
			// aapt resource value: 0x7f060005
			public const int radio_male_btn = 2131099653;
			
			// aapt resource value: 0x7f060015
			public const int save_food_btn = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int serving_size_et = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int settings_button = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int space1 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int space2 = 2131099668;
			
			// aapt resource value: 0x7f06001e
			public const int space3 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int space4 = 2131099680;
			
			// aapt resource value: 0x7f06001c
			public const int space5 = 2131099676;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow1 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int tableRow2 = 2131099661;
			
			// aapt resource value: 0x7f060023
			public const int tb_battery_decay = 2131099683;
			
			// aapt resource value: 0x7f06000b
			public const int textView3 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int textView4 = 2131099662;
			
			// aapt resource value: 0x7f060025
			public const int tv_processed_data = 2131099685;
			
			// aapt resource value: 0x7f06002f
			public const int update_user_btn = 2131099695;
			
			// aapt resource value: 0x7f060017
			public const int user_profile_button = 2131099671;
			
			// aapt resource value: 0x7f06002b
			public const int weight = 2131099691;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int create_user = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int food_page = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int landing_page = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int settings_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int user_activity_layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int user_page = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Hello = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int create_account = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int login = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int sensor_prompt = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
